version: "3.1"
services:
    webserver:
        image: nginx:alpine
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "3000:80"

    php-fpm:
        build: 
            context: .
            dockerfile: docker/php-fpm/Dockerfile
